### ISSUE TITLE
chart failing to render

### ISSUE THREAD

**Issue by martincsumner** [redhat-cop/pathfinder#180] opened 2018-12-12 10:21 UTC
marking an application as database rather than assessable. then calling that same application from another as a dependency causes the bubble chart to fail to render.

From the error it would appear to be a index out of bounds related issue.

**Comment by matallen** [comment] 2018-12-18 20:53
fixed in this commit - https://github.com/redhat-cop/pathfinder/commit/d30a2d5807090476bffcfa8fc754f788042343d1

**Comment by matallen** [comment] 2018-12-18 20:55
The issue was caused by dependencies that had not been assessed and therefore their outbound dependencies was a null rather than a list. This was just poor handling of perfectly valid data, so a correction has been made and committed.

**Closed by matallen** 2018-12-18 20:55 UTC
Labels: bug
